server:
  port: 8080
  servlet:
    context-path: /cloud
spring:
  datasource:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://43.142.4.80:3306/cloudapi?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: cloudapi
    password: 'NDxmQ==LF2g8'
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
  jmx:
    enabled: false
  messages:
    basename: i18n/messages
    encoding: UTF-8
    fallback-to-system-locale: false

# mybatis打印sql语句日志
mybatis:
  # pom中已经配置了过滤
  mapper-locations: classpath*:com/lineying/mapper/*.xml
  # type-aliases-package: com.fg.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 启动时打印日志的访问路径
logging:
  level:
    org:
      springframework:
        web:
          servlet:
            mvc:
              method:
                annotation:
                  RequestMappingHandlerMapping: trace

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
