server:
  port: 8080
  servlet:
    context-path: /cloud
spring:
  datasource:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://43.142.4.80:3306/cloudapi?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: cloudapi
    password: 'NDxmQ==LF2g8'
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
  jmx:
    enabled: false
# mybatis打印sql语句日志
mybatis:
  # pom中已经配置了过滤
  mapper-locations: classpath*:com/lineying/mapper/*.xml
  # type-aliases-package: com.fg.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 启动时打印日志的访问路径
logging:
  level:
    org:
      springframework:
        web:
          servlet:
            mvc:
              method:
                annotation:
                  RequestMappingHandlerMapping: trace

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
config:
  # 这里是服务商的接口-使用时对接接口服务商
  db_api_key: dad4c59fc796e9b53a0390c8407984fb
  db_secret_key: 45a4d0039108e936336194b321c9fdd1
  iv_seed: lyivk4o9lyivk4o9
  mail_sender_name: linesupt
  mail_sender: linesupt@foxmail.com
  mail_password: rrnxgyzerpdfdbfh
  tencentcloud_secret_id: asdfadf
  tencentcloud_secret_key: sdfdf
sms:
    mathcalc:
      sdkAppId:
      secretId:
      secretKey:
      signName:
      templateCodeId:
    scancode:
      sdkAppId:
      secretId:
      secretKey:
      signName:
      templateCodeId:
pay:
  # 应用公钥
  app_pub_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlyJpmWEJQyrbuvgjMqIX28lfi384B1+J0sGWqJqH9yUooKHE1PJbbsRUSjJGJGTI2RyOxijj/GOB5mu8oNdqBndAVjWmfvrSVdV4ct/vDUbJZQGctw3COkWEOp4LvHttpwKrvXp2AmTLmwY4ZbQCqEmujfsEaN+EhK7rt2RU2XMNg1FnaYfdBJGznWCiWuMcdIuzHD2GyvRiG+Q9zpG1j9w2OBIY0ezUsnouwVBPM0hc40UuQDqiYNxA23obvsbHfSsOslaTwCkhNtjeKphRf54CwpQlKZsY4ibl2WMidssWDegHLLsbu5Lg5e+9dz74cy6jt6QIm4jytamkRHejSQIDAQAB
  alipay:
    # 支付宝公钥
    pub_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtOmEVGMkC4Q7Mq0dia8eS0Y/QmX1YqwpUg6pdhDTea4vOkg96amV1KrKz3jfJXIhm26kiB0/tvPpUaYDzyG2z/aAn8/2xQ3UknPzLMMouzDI5/kCxqw8qd5OPs03OhhqE11GN6JttnYiUUJ2SWLvYijAhIOMyatKZFT3j/hEJj+Q5x+e8RqNTHWCB1/rC4k2D4z2SnJ/dG1ZAZu51H/GEW1ShqWCZIyUf8PhH0k5SvCCjVamWVriS3U16eCH/W3YNVEanPNiN22deWiY+Ut1T6Wk7zU9qXSNZuWIuZZfgyI3u6JwE+ZlqMV/VudxhrguTFxhZYALBZ4DQOidkTgI+wIDAQAB
  wxpay:
    # 微信公钥
    pub_key: